"""ZenScat numerical core package."""

from .core import (
    Device1D,
    DiffractionResult,
    Grid1D,
    RayleighCutoffError,
    ScatteringMatrix,
    calc_free_space,
    calc_k,
    calc_layer,
    calc_reflection_side,
    calc_transmission_side,
    convmat1d,
    launch_rcwa_s,
    redheffer_star,
)
from .legacy_io import FDFDResultBundle, ImportedDevice, LegacyResultBundle
from .optimization import OptimizationRequest, OptimizationRun, run_optimization
from .workflows import (
    AnalyticRCWARequest,
    FDFDRequest,
    FDFDRun,
    ImportedRCWARequest,
    PhCRCWARequest,
    RCWARun,
    run_analytic_rcwa,
    run_fdfd,
    run_imported_rcwa,
    run_phc_rcwa,
)

__all__ = [
    "AnalyticRCWARequest",
    "Device1D",
    "DiffractionResult",
    "FDFDRequest",
    "FDFDResultBundle",
    "FDFDRun",
    "Grid1D",
    "ImportedDevice",
    "ImportedRCWARequest",
    "LegacyResultBundle",
    "OptimizationRequest",
    "OptimizationRun",
    "PhCRCWARequest",
    "RCWARun",
    "RayleighCutoffError",
    "ScatteringMatrix",
    "calc_free_space",
    "calc_k",
    "calc_layer",
    "calc_reflection_side",
    "calc_transmission_side",
    "convmat1d",
    "launch_rcwa_s",
    "redheffer_star",
    "run_analytic_rcwa",
    "run_fdfd",
    "run_imported_rcwa",
    "run_optimization",
    "run_phc_rcwa",
]
