"""Pure Python RCWA building blocks."""

from .control import (
    CancellationToken,
    ProgressCallback,
    SimulationCancelled,
    checkpoint,
)
from .device import (
    InterfaceParams,
    LegacyDevice,
    LegacyGrid,
    build_legacy_device,
    build_legacy_grid,
    sample_interface_profile,
)
from .fdfd2d import (
    DEFAULT_DISPERSION_COEFFICIENTS,
    FDFDDevice,
    FDFDGrid,
    FDFDResult,
    addupml2d,
    build_fdfd_device,
    build_fdfd_grid,
    dispersion_refractive_indices,
    fdfd_2d,
    yeeder2d,
)
from .phc import (
    PhCDevice,
    PhCGrid,
    PhCInterfaceParams,
    build_phc_device,
    build_phc_grid,
    launch_rcwa_s_phc,
)
from .phc_fdfd import PhCFDFDDevice, build_phc_fdfd_device
from .rcwa1d import (
    Device1D,
    DiffractionResult,
    Grid1D,
    RayleighCutoffError,
    ScatteringMatrix,
    calc_free_space,
    calc_k,
    calc_layer,
    calc_reflection_side,
    calc_transmission_side,
    convmat1d,
    launch_rcwa_s,
    redheffer_star,
)
from .rcwa1d_t import launch_rcwa_t

__all__ = [
    "DEFAULT_DISPERSION_COEFFICIENTS",
    "CancellationToken",
    "Device1D",
    "DiffractionResult",
    "FDFDDevice",
    "FDFDGrid",
    "FDFDResult",
    "Grid1D",
    "InterfaceParams",
    "LegacyDevice",
    "LegacyGrid",
    "PhCDevice",
    "PhCFDFDDevice",
    "PhCGrid",
    "PhCInterfaceParams",
    "ProgressCallback",
    "RayleighCutoffError",
    "ScatteringMatrix",
    "SimulationCancelled",
    "addupml2d",
    "build_fdfd_device",
    "build_fdfd_grid",
    "build_legacy_device",
    "build_legacy_grid",
    "build_phc_device",
    "build_phc_fdfd_device",
    "build_phc_grid",
    "calc_free_space",
    "calc_k",
    "calc_layer",
    "calc_reflection_side",
    "calc_transmission_side",
    "checkpoint",
    "convmat1d",
    "dispersion_refractive_indices",
    "fdfd_2d",
    "launch_rcwa_s",
    "launch_rcwa_s_phc",
    "launch_rcwa_t",
    "redheffer_star",
    "sample_interface_profile",
    "yeeder2d",
]
